services:
  cleanarchitecturedb:
    container_name: cleanarchitecturedb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cleanarchitecture
    restart: always
    volumes:
      - ./.container/database:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  cleanarchitectureapi:
    container_name: cleanarchitectureapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Test
      - ASPNETCORE_URLS=http://+:5000
      #- "ConnectionStrings_ConnectionString=Host=cleanarchitecturedb;port=5432;Database=cleanarchitecture;Username=postgres;Password=postgres"
    depends_on:
      - cleanarchitecturedb
    ports:
      - 9003:5000

  serilogseq:
    container_name: serilogseq
    environment:
      - ACCEPT_EULA=Y   
    ports:
      - 5341:5341
      - 8081:80

 #docker compose -f docker-compose.yml -f docker-compose.override.yml up -d
 #dotnet ef migrations add InitialCreate -p src/CleanArchitecture/CleanArchitecture.Infrastructure -s src/CleanArchitecture/CleanArchitecture.Api
